sumando1= float(input("introduzca un numero:"))
sumando2= float(input("introduzca un numero:"))
print("La suma es igual a:",sumando1 + sumando2)
resta1= float(input("introduzca un numero:"))
resta2= float(input("introduzca un numero:"))
print("La resta es igual a:",resta1 - resta2)
multiplicacion1= float(input("introduzca un numero:"))
multiplicacion2= float(input("introduzca un numero:"))
print("La suma es igual a:",multiplicacion1 * multiplicacion2)
division1= float(input("introduzca un numero:"))
division2= float(input("introduzca un numero:"))
print("La division es igual a:",division1 / division2)